#!/usr/bin/env python3

from os import environ
from pathlib import Path
import json
from ultisnips2vscode import UltisnipParser, vim2vscode

def main():
    config = read_config()
    parser = UltisnipParser(
        Path(config["ultisnips-snippets"]).expanduser(),
        Path(config["vscode-snippets"]).expanduser(),
        vim2vscode
    )
    parser.parse_snippets(verbose=True)
    parser.write_snippets()

def read_config():
    """Reads the config file and returns a dictionary containing
    the ultisnips and vscode snippets directories
    """
    config_file = environ.get('UTILSNIPS_TO_VSCODE_CONFIG')
    if config_file is None:
        config_file = Path().home() / '.vscode/ultisnips-vscode.json'
    with open(config_file, 'r') as f:
        data = json.load(f)
    return data


if __name__ == '__main__':
    main()
